apiVersion: v1
kind: Service
metadata: 
  name: birthday-mysql
  labels:
    app: birthday-server
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: birthday-mysql
    tier: mysql
